{
 "title": "Bee-Hive Monitoring Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Inside Temperature",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "target": "Temperature", "type": "timeserie" }
   ]
  },
  {
   "title": "Outside Temperature",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "target": "Temperature", "type": "timeserie" }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "atm" }
   ],
   "targets": [
    { "target": "Barometric", "type": "timeserie" }
   ]
  },
  {
   "title": "Weight",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Celcius" }
   ],
   "targets": [
    { "target": "Temperature", "type": "timeserie" },
    { "target": "Humidity", "type": "timeserie" }
   ]
  },
  {
   "title": "Sound",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "atm" }
   ],
   "targets": [
    { "target": "Barometric", "type": "timeserie" }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Humidity", "type": "timeserie" }
   ]
  },
  {
   "title": "Ambient Light",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "Luminosity", "type": "timeserie" }
   ]
  },
  {
   "title": "Barometric",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "format": "pressurebar",
   "valueName": "current",
   "targets": [
    { "target": "Barometric", "type": "timeserie" }
   ]
  }
 ]
}