{
 "title": "Bee-Hive Monitoring Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Barometric",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "atm" }
   ],
   "targets": [
    { "target": "Barometric", "type": "timeserie" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "g/m³" }
   ],
   "targets": [
    { "target": "Humidity", "type": "timeserie" }
   ]
  },
  {
   "title": "Luminosity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "lux" }
   ],
   "targets": [
    { "target": "Luminosity", "type": "timeserie" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Celcius" }
   ],
   "targets": [
    { "target": "Temperature", "type": "timeserie" }
   ]
  }
 ]
}